# Generated by Django 4.0.4 on 2022-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, verbose_name='Код')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('img', models.ImageField(blank=True, upload_to='product_img/', verbose_name='Изображение-1')),
                ('img_1', models.ImageField(blank=True, upload_to='product_img/', verbose_name='Изображение-2')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Имя')),
                ('ogrn', models.IntegerField(blank=True, unique=True, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
    ]
