# Generated by Django 4.0.4 on 2022-07-15 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildberries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
